; This file was auto-generated by drush make
core = 7.12

api = 2
projects[drupal][version] = "7.12"

; Modules
projects[views_bulk_operations][version] = "3.0-rc1"

projects[backup_migrate][version] = "2.2"

projects[ctools][version] = "1.0-rc1"

projects[captcha][version] = "1.0-beta2"

projects[cm_checklist][version] = "1.x-dev"

projects[cm_show][version] = "1.x-dev"

projects[cm_slideshow][version] = "1.x-dev"

projects[entity][version] = "1.0-rc1"

projects[features][version] = "1.0-beta6"

projects[field_group][version] = "1.1"

projects[fontyourface][version] = "2.2"

projects[jquery_update][version] = "2.2"

projects[legal][version] = "1.2"

projects[om_crew_connect][version] = "2.0-beta2"

projects[pbcore][version] = "1.0-beta1"

projects[profile2][version] = "1.2"

projects[recaptcha][version] = "1.7"

projects[views][version] = "3.3"

projects[views_send][version] = "1.x-dev"

projects[webform][version] = "3.17"

projects[wysiwyg][version] = "2.1"

; Themes
projects[omega][version] = "3.1"

projects[cm_theme][version] = "1.x-dev"

